name: Deploy

on: [push]

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Publish Telegram Lambda
      run: dotnet publish ./FloppyNet.Aws.TelegramLambda/ -c Release -o ../output/FloppyNet.Aws.TelegramLambda
    
    - name: Publish Wordle Lambda
      run: dotnet publish ./FloppyNet.Aws.WordleLambda/ -c Release -r linux-x64 --no-self-contained -o ../output/FloppyNet.Aws.WordleLambda
    
    - name: Publish Reminder Lambda
      run: dotnet publish ./FloppyNet.Aws.ReminderLambda/ -c Release -o ../output/FloppyNet.Aws.ReminderLambda

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    
    - name: Build Web App
      working-directory: ./FloppyNet.UI/floppy-net
      run: npm install && npm run build
      
    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy
      run: cdk deploy --require-approval=never
      env:
        App__Account: ${{ secrets.AWS_ACCOUNT_ID }}
        App__Region: ${{ secrets.AWS_REGION }}
        Telegram__SecretKey: ${{ secrets.TELEGRAM_SECRET }}
        Telegram__BotCredentials: ${{ secrets.TELEGRAM_BOT_CREDENTIALS }}
        Telegram__ChatId: ${{ secrets.TELEGRAM_CHAT_ID }}
        Stack__Name: ${{ vars.CDK_STACK_NAME }}
        Stack__DomainRoot: ${{ vars.CDK_STACK_DOMAIN }}
        Stack__HostedZoneId: ${{ secrets.CDK_HOSTED_ZONE_ID }}
